-- Заполнение таблицы регионов
INSERT INTO regions (name) VALUES
('Алматинская область'),
('Акмолинская область'),
('Туркестанская область'),
('Карагандинская область'),
('Актюбинская область'),
('Жамбылская область'),
('Павлодарская область'),
('Восточно-Казахстанская область'),
('Атырауская область'),
('Костанайская область'),
('Кызылординская область'),
('Западно-Казахстанская область'),
('Северо-Казахстанская область')
ON CONFLICT (name) DO NOTHING;

-- Заполнение таблицы городов
INSERT INTO cities (name, region_id) VALUES
('Алматы', (SELECT id FROM regions WHERE name = 'Алматинская область')),
('Астана', (SELECT id FROM regions WHERE name = 'Акмолинская область')),
('Шымкент', (SELECT id FROM regions WHERE name = 'Туркестанская область')),
('Караганда', (SELECT id FROM regions WHERE name = 'Карагандинская область')),
('Актобе', (SELECT id FROM regions WHERE name = 'Актюбинская область')),
('Тараз', (SELECT id FROM regions WHERE name = 'Жамбылская область')),
('Павлодар', (SELECT id FROM regions WHERE name = 'Павлодарская область')),
('Усть-Каменогорск', (SELECT id FROM regions WHERE name = 'Восточно-Казахстанская область')),
('Семей', (SELECT id FROM regions WHERE name = 'Восточно-Казахстанская область')),
('Атырау', (SELECT id FROM regions WHERE name = 'Атырауская область')),
('Костанай', (SELECT id FROM regions WHERE name = 'Костанайская область')),
('Кызылорда', (SELECT id FROM regions WHERE name = 'Кызылординская область')),
('Уральск', (SELECT id FROM regions WHERE name = 'Западно-Казахстанская область')),
('Петропавловск', (SELECT id FROM regions WHERE name = 'Северо-Казахстанская область')),
('Кокшетау', (SELECT id FROM regions WHERE name = 'Акмолинская область')),
('Талдыкорган', (SELECT id FROM regions WHERE name = 'Алматинская область')),
('Экибастуз', (SELECT id FROM regions WHERE name = 'Павлодарская область')),
('Туркестан', (SELECT id FROM regions WHERE name = 'Туркестанская область'))
ON CONFLICT (name) DO NOTHING;

-- Заполнение таблицы районов Алматы
INSERT INTO districts (name, city_id) VALUES
('Алатауский', (SELECT id FROM cities WHERE name = 'Алматы')),
('Алмалинский', (SELECT id FROM cities WHERE name = 'Алматы')),
('Ауэзовский', (SELECT id FROM cities WHERE name = 'Алматы')),
('Бостандыкский', (SELECT id FROM cities WHERE name = 'Алматы')),
('Жетысуский', (SELECT id FROM cities WHERE name = 'Алматы')),
('Медеуский', (SELECT id FROM cities WHERE name = 'Алматы')),
('Наурызбайский', (SELECT id FROM cities WHERE name = 'Алматы')),
('Турксибский', (SELECT id FROM cities WHERE name = 'Алматы'))
ON CONFLICT (name, city_id) DO NOTHING; 

INSERT INTO microdistricts (name, district_id) VALUES
('13-й', (SELECT id FROM districts WHERE name = 'Алатауский')),
('6-й градокомплекс', (SELECT id FROM districts WHERE name = 'Алатауский')),
('71-й разъезд', (SELECT id FROM districts WHERE name = 'Алатауский')),
('АДК', (SELECT id FROM districts WHERE name = 'Алатауский')),
('Айгерим-1', (SELECT id FROM districts WHERE name = 'Алатауский')),
('Айгерим-2', (SELECT id FROM districts WHERE name = 'Алатауский')),
('Акбулак', (SELECT id FROM districts WHERE name = 'Алатауский')),
('Аккент', (SELECT id FROM districts WHERE name = 'Алатауский')),
('Алгабас', (SELECT id FROM districts WHERE name = 'Алатауский')),
('Байбесик', (SELECT id FROM districts WHERE name = 'Алатауский')),
('Боралдай (Бурундай)', (SELECT id FROM districts WHERE name = 'Алатауский')),
('Ботакоз', (SELECT id FROM districts WHERE name = 'Алатауский')),
('Гажайып', (SELECT id FROM districts WHERE name = 'Алатауский')),
('Дарабоз', (SELECT id FROM districts WHERE name = 'Алатауский')),
('Дархан', (SELECT id FROM districts WHERE name = 'Алатауский')),
('Заря Востока', (SELECT id FROM districts WHERE name = 'Алатауский')),
('Зердели', (SELECT id FROM districts WHERE name = 'Алатауский')),
('Карасу', (SELECT id FROM districts WHERE name = 'Алатауский')),
('Коккайнар', (SELECT id FROM districts WHERE name = 'Алатауский')),
('Курылысшы', (SELECT id FROM districts WHERE name = 'Алатауский')),
('Мадениет', (SELECT id FROM districts WHERE name = 'Алатауский')),
('Нуркент', (SELECT id FROM districts WHERE name = 'Алатауский')),
('Ожет', (SELECT id FROM districts WHERE name = 'Алатауский')),
('Рахат', (SELECT id FROM districts WHERE name = 'Алатауский')),
('Самгау', (SELECT id FROM districts WHERE name = 'Алатауский')),
('Саялы', (SELECT id FROM districts WHERE name = 'Алатауский')),
('Теректы', (SELECT id FROM districts WHERE name = 'Алатауский')),
('Томирис', (SELECT id FROM districts WHERE name = 'Алатауский')),
('Трудовик', (SELECT id FROM districts WHERE name = 'Алатауский')),
('Туркестан', (SELECT id FROM districts WHERE name = 'Алатауский')),
('Улжан-1', (SELECT id FROM districts WHERE name = 'Алатауский')),
('Улжан-2', (SELECT id FROM districts WHERE name = 'Алатауский')),
('Шанырак-1', (SELECT id FROM districts WHERE name = 'Алатауский')),
('Шанырак-2', (SELECT id FROM districts WHERE name = 'Алатауский')),
('Шанырак-3', (SELECT id FROM districts WHERE name = 'Алатауский')),
('Шанырак-4', (SELECT id FROM districts WHERE name = 'Алатауский')),
('Шанырак-5', (SELECT id FROM districts WHERE name = 'Алатауский')),
('Шанырак-6', (SELECT id FROM districts WHERE name = 'Алатауский')),
('Шапагат', (SELECT id FROM districts WHERE name = 'Алатауский'));

INSERT INTO microdistricts (name, district_id) VALUES
('Тастак-2', (SELECT id FROM districts WHERE name = 'Алмалинский')),
('Тастак-3', (SELECT id FROM districts WHERE name = 'Алмалинский'));

INSERT INTO microdistricts (name, district_id) VALUES
('Акбулак', (SELECT id FROM districts WHERE name = 'Ауэзовский')),
('Аксай-1', (SELECT id FROM districts WHERE name = 'Ауэзовский')),
('Аксай-1А', (SELECT id FROM districts WHERE name = 'Ауэзовский')),
('Аксай-2', (SELECT id FROM districts WHERE name = 'Ауэзовский')),
('Аксай-2А', (SELECT id FROM districts WHERE name = 'Ауэзовский')),
('Аксай-3', (SELECT id FROM districts WHERE name = 'Ауэзовский')),
('Аксай-3А', (SELECT id FROM districts WHERE name = 'Ауэзовский')),
('Аксай-3Б', (SELECT id FROM districts WHERE name = 'Ауэзовский')),
('Аксай-4', (SELECT id FROM districts WHERE name = 'Ауэзовский')),
('Аксай-5', (SELECT id FROM districts WHERE name = 'Ауэзовский')),
('Алмас', (SELECT id FROM districts WHERE name = 'Ауэзовский')),
('Алтын Бесик', (SELECT id FROM districts WHERE name = 'Ауэзовский')),
('Астана', (SELECT id FROM districts WHERE name = 'Ауэзовский')),
('Баянаул', (SELECT id FROM districts WHERE name = 'Ауэзовский')),
('Достык', (SELECT id FROM districts WHERE name = 'Ауэзовский')),
('Дубок (Шабыт)', (SELECT id FROM districts WHERE name = 'Ауэзовский')),
('Дубок-2', (SELECT id FROM districts WHERE name = 'Ауэзовский')),
('Жазира', (SELECT id FROM districts WHERE name = 'Ауэзовский')),
('Жетысу-1', (SELECT id FROM districts WHERE name = 'Ауэзовский')),
('Жетысу-2', (SELECT id FROM districts WHERE name = 'Ауэзовский')),
('Жетысу-3', (SELECT id FROM districts WHERE name = 'Ауэзовский')),
('Жетысу-4', (SELECT id FROM districts WHERE name = 'Ауэзовский')),
('Мамыр', (SELECT id FROM districts WHERE name = 'Ауэзовский')),
('Мамыр-1', (SELECT id FROM districts WHERE name = 'Ауэзовский')),
('Мамыр-2', (SELECT id FROM districts WHERE name = 'Ауэзовский')),
('Мамыр-3', (SELECT id FROM districts WHERE name = 'Ауэзовский')),
('Мамыр-4', (SELECT id FROM districts WHERE name = 'Ауэзовский')),
('Мамыр-7', (SELECT id FROM districts WHERE name = 'Ауэзовский')),
('Сайран', (SELECT id FROM districts WHERE name = 'Ауэзовский')),
('Тастак-1', (SELECT id FROM districts WHERE name = 'Ауэзовский')),
('Таугуль', (SELECT id FROM districts WHERE name = 'Ауэзовский')),
('Таугуль-1', (SELECT id FROM districts WHERE name = 'Ауэзовский')),
('Таугуль-2', (SELECT id FROM districts WHERE name = 'Ауэзовский')),
('Таугуль-3', (SELECT id FROM districts WHERE name = 'Ауэзовский')),
('Тепличный', (SELECT id FROM districts WHERE name = 'Ауэзовский')),
('№1', (SELECT id FROM districts WHERE name = 'Ауэзовский')),
('№10', (SELECT id FROM districts WHERE name = 'Ауэзовский')),
('№10 А', (SELECT id FROM districts WHERE name = 'Ауэзовский')),
('№11', (SELECT id FROM districts WHERE name = 'Ауэзовский')),
('№12', (SELECT id FROM districts WHERE name = 'Ауэзовский')),
('№2', (SELECT id FROM districts WHERE name = 'Ауэзовский')),
('№3', (SELECT id FROM districts WHERE name = 'Ауэзовский')),
('№4', (SELECT id FROM districts WHERE name = 'Ауэзовский')),
('№5', (SELECT id FROM districts WHERE name = 'Ауэзовский')),
('№6', (SELECT id FROM districts WHERE name = 'Ауэзовский')),
('№7', (SELECT id FROM districts WHERE name = 'Ауэзовский')),
('№8', (SELECT id FROM districts WHERE name = 'Ауэзовский')),
('№9', (SELECT id FROM districts WHERE name = 'Ауэзовский'));

INSERT INTO microdistricts (name, district_id) VALUES
('Актобе', (SELECT id FROM districts WHERE name = 'Бостандыкский')),
('Алмагуль', (SELECT id FROM districts WHERE name = 'Бостандыкский')),
('Архат', (SELECT id FROM districts WHERE name = 'Бостандыкский')),
('Баганашыл', (SELECT id FROM districts WHERE name = 'Бостандыкский')),
('Ерменсай', (SELECT id FROM districts WHERE name = 'Бостандыкский')),
('Казахфильм', (SELECT id FROM districts WHERE name = 'Бостандыкский')),
('Керемет', (SELECT id FROM districts WHERE name = 'Бостандыкский')),
('Коктем-1', (SELECT id FROM districts WHERE name = 'Бостандыкский')),
('Коктем-2', (SELECT id FROM districts WHERE name = 'Бостандыкский')),
('Коктем-3', (SELECT id FROM districts WHERE name = 'Бостандыкский')),
('Мирас', (SELECT id FROM districts WHERE name = 'Бостандыкский')),
('Нур Алатау', (SELECT id FROM districts WHERE name = 'Бостандыкский')),
('Нурлытау (Энергетик)', (SELECT id FROM districts WHERE name = 'Бостандыкский')),
('Орбита-1', (SELECT id FROM districts WHERE name = 'Бостандыкский')),
('Орбита-2', (SELECT id FROM districts WHERE name = 'Бостандыкский')),
('Орбита-3', (SELECT id FROM districts WHERE name = 'Бостандыкский')),
('Орбита-4', (SELECT id FROM districts WHERE name = 'Бостандыкский')),
('Хан Тенгри', (SELECT id FROM districts WHERE name = 'Бостандыкский'));

INSERT INTO microdistricts (name, district_id) VALUES
('Айнабулак-1', (SELECT id FROM districts WHERE name = 'Жетысуский')),
('Айнабулак-2', (SELECT id FROM districts WHERE name = 'Жетысуский')),
('Айнабулак-3', (SELECT id FROM districts WHERE name = 'Жетысуский')),
('Айнабулак-4', (SELECT id FROM districts WHERE name = 'Жетысуский')),
('Дорожник', (SELECT id FROM districts WHERE name = 'Жетысуский')),
('Кемел (Первомайское)', (SELECT id FROM districts WHERE name = 'Жетысуский')),
('Кокжиек', (SELECT id FROM districts WHERE name = 'Жетысуский')),
('Кулагер', (SELECT id FROM districts WHERE name = 'Жетысуский'));

INSERT INTO microdistricts (name, district_id) VALUES
('Аккайын', (SELECT id FROM districts WHERE name = 'Медеуский')),
('Алатау (ИЯФ)', (SELECT id FROM districts WHERE name = 'Медеуский')),
('Аскартау', (SELECT id FROM districts WHERE name = 'Медеуский')),
('Атырау', (SELECT id FROM districts WHERE name = 'Медеуский')),
('Бутаковка', (SELECT id FROM districts WHERE name = 'Медеуский')),
('Горный Гигант', (SELECT id FROM districts WHERE name = 'Медеуский')),
('Думан-1', (SELECT id FROM districts WHERE name = 'Медеуский')),
('Думан-2', (SELECT id FROM districts WHERE name = 'Медеуский')),
('Каменское плато', (SELECT id FROM districts WHERE name = 'Медеуский')),
('Кенсай', (SELECT id FROM districts WHERE name = 'Медеуский')),
('Коктобе', (SELECT id FROM districts WHERE name = 'Медеуский')),
('Кольсай', (SELECT id FROM districts WHERE name = 'Медеуский')),
('Самал', (SELECT id FROM districts WHERE name = 'Медеуский')),
('Самал-1', (SELECT id FROM districts WHERE name = 'Медеуский')),
('Самал-2', (SELECT id FROM districts WHERE name = 'Медеуский')),
('Самал-3', (SELECT id FROM districts WHERE name = 'Медеуский')),
('Сулусай', (SELECT id FROM districts WHERE name = 'Медеуский')),
('Тау Самал', (SELECT id FROM districts WHERE name = 'Медеуский')),
('Юбилейный', (SELECT id FROM districts WHERE name = 'Медеуский'));

INSERT INTO microdistricts (name, district_id) VALUES
('Акжар', (SELECT id FROM districts WHERE name = 'Наурызбайский')),
('Галамат', (SELECT id FROM districts WHERE name = 'Наурызбайский')),
('Дарын', (SELECT id FROM districts WHERE name = 'Наурызбайский')),
('Жайлау', (SELECT id FROM districts WHERE name = 'Наурызбайский')),
('Жайлым', (SELECT id FROM districts WHERE name = 'Наурызбайский')),
('Калкаман-1', (SELECT id FROM districts WHERE name = 'Наурызбайский')),
('Калкаман-2', (SELECT id FROM districts WHERE name = 'Наурызбайский')),
('Калкаман-3', (SELECT id FROM districts WHERE name = 'Наурызбайский')),
('Карагайлы', (SELECT id FROM districts WHERE name = 'Наурызбайский')),
('Каргалы', (SELECT id FROM districts WHERE name = 'Наурызбайский')),
('Курамыс', (SELECT id FROM districts WHERE name = 'Наурызбайский')),
('Рахат', (SELECT id FROM districts WHERE name = 'Наурызбайский')),
('Тастыбулак', (SELECT id FROM districts WHERE name = 'Наурызбайский')),
('Таужол', (SELECT id FROM districts WHERE name = 'Наурызбайский')),
('Таусамал', (SELECT id FROM districts WHERE name = 'Наурызбайский')),
('Шугыла', (SELECT id FROM districts WHERE name = 'Наурызбайский'));

INSERT INTO microdistricts (name, district_id) VALUES
('13-й военный городок', (SELECT id FROM districts WHERE name = 'Турксибский')),
('16-й военный городок', (SELECT id FROM districts WHERE name = 'Турксибский')),
('Алтай-1', (SELECT id FROM districts WHERE name = 'Турксибский')),
('Алтай-2', (SELECT id FROM districts WHERE name = 'Турксибский')),
('Альмерек', (SELECT id FROM districts WHERE name = 'Турксибский')),
('Жас Канат', (SELECT id FROM districts WHERE name = 'Турксибский')),
('Жулдыз-1', (SELECT id FROM districts WHERE name = 'Турксибский')),
('Жулдыз-2', (SELECT id FROM districts WHERE name = 'Турксибский')),
('Кайрат', (SELECT id FROM districts WHERE name = 'Турксибский')),
('Маяк', (SELECT id FROM districts WHERE name = 'Турксибский')),
('Нуршашкан (Колхозши)', (SELECT id FROM districts WHERE name = 'Турксибский'));